[package]
name = "cargo-reedme"
version = "0.4.0"
edition = "2024"
description = "Generate README.md from doc comments in lib.rs"
rust-version = "1.93"
authors = ["Nik Revenco <pm@nikrev.com>"]
repository = "https://github.com/nik-rev/cargo-reedme"
keywords = ["readme", "documentation", "cargo", "subcommand", "tool"]
categories = ["development-tools::cargo-plugins", "development-tools", "text-processing", "command-line-interface", "development-tools"]
license = "MIT OR Apache-2.0"

[features]
__failing_links = []

[dependencies]
diff = "0.1.3"
cargo_metadata = "0.23.1"
clap = { version = "4.5.54", features = ["derive", "unstable-markdown", "wrap_help"] }
clap-cargo = { version = "0.18.3", features = ["cargo_metadata"] }
camino = { version = "1.2.2", features = ["serde1"] }
eyre = "0.6.12"
rustdoc-json = "0.9.8"
fs-err = "3.2.2"
serde_json = "1.0.149"
serde = { version = "1.0.228", features = ["derive"] }
rustdoc-types = "0.57.0"
pulldown-cmark = "0.13.0"
itertools = "0.14.0"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
clap-verbosity-flag = { version = "3.0.4", default-features = false, features = ["tracing"] }
rangemap = "1.7.1"
regex = "1.12.2"
docstr = "0.4.6"
rayon = "1.11.0"
colored_json = "5.0.0"
semver = { version = "1.0.27", features = ["serde"] }
konst = "0.2"
anstream = "0.6.21"
term = "1.2.1"
microtemplate = "1.0.3"
toml = "1.0.3"
serde_with = "3.16.1"

[dev-dependencies]
rust-playground-top-crates = { version = "=0.1.7", git = "https://github.com/rust-lang/rust-playground.git" }
anstream = "0.6.21"
ureq = "3.2.0"
flate2 = "1.0"
tar = "0.4"
assert_fs = { version = "1.1.3", features = ["color-auto"] }
assert2 = "0.4.0"
auto-default = "0.2.3"
similar = "2.7.0"
pretty_assertions = "1.4.1"
simply_colored = "0.1.6"
