[package]
name = "cargo-reedme"
version = "0.1.0"
edition = "2024"

[dependencies]
cargo_metadata = "0.23.1"
clap = { version = "4.5.54", features = ["derive", "unstable-markdown", "wrap_help"] }
clap-cargo = { version = "0.18.3", features = ["cargo_metadata"] }
camino = { version = "1.2.2", features = ["serde1"] }
color-eyre = "0.6.5"
eyre = "0.6.12"
rustdoc-json = "0.9.8"
fs-err = "3.2.2"
serde_json = "1.0.149"
serde = { version = "1.0.228", features = ["derive"] }
rustdoc-types = "0.57.0"
pulldown-cmark = "0.13.0"
pulldown-cmark-to-cmark = "22.0.0"
itertools = "0.14.0"
pretty_assertions = "1.4.1"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
clap-verbosity-flag = { version = "3.0.4", default-features = false, features = ["tracing"] }
rangemap = "1.7.1"
regex = "1.12.2"
docstr = "0.4.6"
rayon = "1.11.0"

[dev-dependencies]
anstream = "0.6.21"
simply_colored = "0.1.4"
