//! Handles logic for inserting generated README files into existing README files

use std::ops::Range;

use docstr::docstr;
use itertools::Itertools;
use serde::Deserialize;
use serde::Serialize;

use crate::World;
use crate::config::Config;

/// Represents contents of the new README file
#[derive(Serialize, Deserialize)]
pub struct ReadmeFile {
    /// This is the part generated by US.
    ///
    /// We took documentation comments and transformed them, the end result is this field
    pub contents: String,
    /// If we are updating the user's README file, as will usually be the case - then this
    /// field contains information to let us know that
    pub meta: ReadmeContentsMeta,
}

/// Contains metadata about how the README is created
#[derive(Serialize, Deserialize)]
pub enum ReadmeContentsMeta {
    /// The README file did not exist before, so we created it
    NewlyCreated,
    /// README file already existed, and we inserted our generated README in the middle of it
    InsertedIntoUsersReadme(UsersReadmeParts),
    /// README file already existed, but there's no marker to tell us where we should insert our README
    ///
    /// This is considered an error. It is a variant instead of wrapping the main type
    /// in Result because it is useful to be able to access generated README content
    ErrorMarkerMissing,
}

/// This locates range of lines for the INFO section in the README file
///
/// This section is ignored by us when comparing diffs
pub fn locate_info_section(content: &str) -> Option<Range<usize>> {
    let lines = content.lines().collect_vec();

    let (first, _) = lines
        .iter()
        .find_position(|line| line.contains(ReadmeFile::INFO_START))?;
    let (last, _) = lines
        .iter()
        .find_position(|line| line.contains(ReadmeFile::INFO_END))?;

    Some(first..last)
}

/// Normalizes the current README by making its INFO section
/// be the same as the new readme
///
/// We want to have the freedom to update the INFO section anytime,
/// so changes to it should not fail the CI
pub fn normalize_new_readme(current_readme: &str, new_readme: &str) -> String {
    let new_readme = new_readme.trim_end();

    // where the INFO section sits in both versions
    let current_info_range = locate_info_section(current_readme).unwrap_or_default();
    let new_info_range = locate_info_section(new_readme).unwrap_or_default();

    // extract the INFO lines from the CURRENT readme
    let current_info_lines = current_readme
        .lines()
        .enumerate()
        .filter_map(|(i, line)| current_info_range.contains(&i).then_some(line));

    let new_readme_lines = new_readme.lines().collect_vec();

    // reconstruct the README:
    // [new content before INFO] + [old INFO section] + [new content after INFO]
    new_readme_lines[..new_info_range.start]
        .iter()
        .copied()
        .chain(current_info_lines)
        .chain(new_readme_lines[new_info_range.end..].iter().copied())
        .join("\n")
}

impl ReadmeFile {
    const INFO_START: &str = "cargo-reedme: info-start";
    const INFO_END: &str = "cargo-reedme: info-end";

    /// Generate the NOTE that will be used to let users know about where
    /// the generated README section came from
    fn generate_note(world: &World, config: &Config) -> String {
        #[derive(microtemplate::Substitutions)]
        struct Substitute<'a> {
            args: &'a str,
            toolchain: &'a str,
        }

        let note = microtemplate::render(&config.note, Substitute {
            args: &world.args.iter().join(" "),
            toolchain: &world.toolchain,
        });

        // indent every line so it stands out more
        //
        // + remove trailing whitespace
        let note = note
            .lines()
            .map(|line| format!("    {line}").trim_end().to_string())
            .join("\n");

        docstr!(format!
            /// <!-- {}
            ///
            /// {note}
            ///
            /// {} -->
            Self::INFO_START, Self::INFO_END
        )
    }

    /// Creates the output README file string.
    ///
    /// Returns `false` as the 2nd return when we can't figure out what the contents should be,
    /// because the marker is not present
    pub fn to_readme(&self, world: &World, config: &Config) -> Option<String> {
        let contents = &self.contents;

        let alert = Self::generate_note(world, config);

        match &self.meta {
            ReadmeContentsMeta::NewlyCreated => {
                Some(docstr!(format!
                    /// {}
                    ///
                    /// {alert}
                    ///
                    /// {contents}
                    ///
                    /// {}
                    ///
                    UsersReadmeParts::MARKER_INSERT_START, UsersReadmeParts::MARKER_INSERT_END
                ))
            }
            ReadmeContentsMeta::InsertedIntoUsersReadme(parts) => {
                Some(docstr!(format!
                    /// {}{}
                    ///
                    /// {alert}
                    ///
                    /// {}
                    ///
                    /// {}{}
                    parts.before, UsersReadmeParts::MARKER_INSERT_START, contents, UsersReadmeParts::MARKER_INSERT_END, parts.after
                ))
            }
            ReadmeContentsMeta::ErrorMarkerMissing => None,
        }
    }
}

#[derive(Serialize, Deserialize)]
pub struct UsersReadmeParts {
    pub before: String,
    after: String,
}

impl UsersReadmeParts {
    const MARKER_INSERT: &'static str = "<!-- cargo-reedme -->";
    const MARKER_INSERT_START: &'static str = "<!-- cargo-reedme: start -->";
    const MARKER_INSERT_END: &'static str = "<!-- cargo-reedme: end -->";

    pub fn new(original_readme: &str) -> Option<Self> {
        let (before, after) = original_readme
            .split_once(Self::MARKER_INSERT_START)
            .and_then(|(before, remaining)| {
                remaining
                    .rsplit_once(Self::MARKER_INSERT_END)
                    .map(|(_previously_inserted_by_us, after)| (before, after))
            })
            .or_else(|| original_readme.split_once(Self::MARKER_INSERT))?;

        Some(Self {
            before: before.to_string(),
            after: after.to_string(),
        })
    }
}

#[cfg(test)]
mod tests {
    use pretty_assertions::assert_str_eq;

    use super::*;

    fn alert() -> String {
        ReadmeFile::generate_note(&World::default(), &Config::default())
    }

    fn t(original: &str, insert: &str) -> Option<String> {
        UsersReadmeParts::new(original).and_then(|parts| {
            ReadmeFile {
                contents: insert.to_string(),
                meta: ReadmeContentsMeta::InsertedIntoUsersReadme(parts),
            }
            .to_readme(&World::default(), &Config::default())
        })
    }

    #[test]
    fn missing_marker() {
        assert_eq!(
            t(
                docstr!(
                    /// Header
                    ///
                    /// Footer
                ),
                "...",
            ),
            None
        );
    }

    /// Creating README file for the first time will insert markers,
    /// so subsequent invocations won't error
    #[test]
    fn create() {
        assert_str_eq!(
            ReadmeFile {
                contents: docstr!(
                    /// first
                )
                .to_string(),
                meta: ReadmeContentsMeta::NewlyCreated
            }
            .to_readme(&World::default(), &Config::default())
            .unwrap(),
            docstr!(format!
                /// <!-- cargo-reedme: start -->
                ///
                /// {}
                ///
                /// first
                ///
                /// <!-- cargo-reedme: end -->
                ///
                alert()
            )
        );
    }

    #[test]
    fn insert() {
        let output = t(
            docstr!(
                /// Header
                ///
                /// <!-- cargo-reedme -->
                ///
                /// Footer
            ),
            "hello world",
        )
        .unwrap();

        assert_str_eq!(
            output,
            docstr!(format!
                /// Header
                ///
                /// <!-- cargo-reedme: start -->
                ///
                /// {}
                ///
                /// hello world
                ///
                /// <!-- cargo-reedme: end -->
                ///
                /// Footer
                alert()
            )
        );
    }

    #[test]
    fn update() {
        let output = t(
            docstr!(
                /// Header
                ///
                /// <!-- cargo-reedme: start -->
                ///
                /// hello world
                ///
                /// <!-- cargo-reedme: end -->
                ///
                /// Footer
            ),
            "goodbye moon",
        )
        .unwrap();

        assert_str_eq!(
            output,
            docstr!(format!
                /// Header
                ///
                /// <!-- cargo-reedme: start -->
                ///
                /// {}
                ///
                /// goodbye moon
                ///
                /// <!-- cargo-reedme: end -->
                ///
                /// Footer
                alert()
            )
        );
    }
}
