//! Handles logic for inserting generated README files into existing README files

use docstr::docstr;
use serde::{Deserialize, Serialize};

/// Represents contents of the new README file
#[derive(Serialize, Deserialize)]
pub struct ReadmeFile {
    /// This is the part generated by US.
    ///
    /// We took documentation comments and transformed them, the end result is this field
    pub contents: String,
    /// If we are updating the user's README file, as will usually be the case - then this
    /// field contains information to let us know that
    pub meta: ReadmeContentsMeta,
}

/// Contains metadata about how the README is created
#[derive(Serialize, Deserialize)]
pub enum ReadmeContentsMeta {
    /// The README file did not exist before, so we created it
    NewlyCreated,
    /// README file already existed, and we inserted our generated README in the middle of it
    InsertedIntoUsersReadme(UsersReadmeParts),
    /// README file already existed, but there's no marker to tell us where we should insert our README
    ///
    /// This is considered an error. It is a variant instead of wrapping the main type
    /// in Result because it is useful to be able to access generated README content
    ErrorMarkerMissing,
}

impl ReadmeFile {
    /// Creates the output README file string.
    ///
    /// Returns `false` as the 2nd return when we can't figure out what the contents should be,
    /// because the marker is not present
    pub fn to_readme(&self) -> Option<String> {
        let contents = &self.contents;

        match &self.meta {
            ReadmeContentsMeta::NewlyCreated => {
                Some(docstr!(format!
                    /// {}
                    ///
                    /// {contents}
                    ///
                    /// {}
                    ///
                    UsersReadmeParts::MARKER_INSERT_START, UsersReadmeParts::MARKER_INSERT_END
                ))
            }
            ReadmeContentsMeta::InsertedIntoUsersReadme(parts) => {
                Some(docstr!(format!
                    /// {}{}
                    ///
                    /// {}
                    ///
                    /// {}{}
                    parts.before, UsersReadmeParts::MARKER_INSERT_START, contents, UsersReadmeParts::MARKER_INSERT_END, parts.after
                ))
            }
            ReadmeContentsMeta::ErrorMarkerMissing => None,
        }
    }
}

#[derive(Serialize, Deserialize)]
pub struct UsersReadmeParts {
    before: String,
    after: String,
}

impl UsersReadmeParts {
    const MARKER_INSERT: &'static str = "<!-- cargo-reedme -->";
    const MARKER_INSERT_START: &'static str = "<!-- cargo-reedme: start -->";
    const MARKER_INSERT_END: &'static str = "<!-- cargo-reedme: end -->";

    pub fn new(original_readme: &str) -> Option<Self> {
        let (before, after) = original_readme
            .split_once(Self::MARKER_INSERT)
            .or_else(|| {
                original_readme
                    .split_once(Self::MARKER_INSERT_START)
                    .and_then(|(before, remaining)| {
                        remaining
                            .split_once(Self::MARKER_INSERT_END)
                            .map(|(_previously_inserted_by_us, after)| (before, after))
                    })
            })?;

        Some(Self {
            before: before.to_string(),
            after: after.to_string(),
        })
    }
}

#[cfg(test)]
mod tests {
    use pretty_assertions::assert_str_eq;

    use super::*;

    fn t(original: &str, insert: &str) -> Option<String> {
        UsersReadmeParts::new(original).and_then(|parts| {
            ReadmeFile {
                contents: insert.to_string(),
                meta: ReadmeContentsMeta::InsertedIntoUsersReadme(parts),
            }
            .to_readme()
        })
    }

    #[test]
    fn missing_marker() {
        assert_eq!(
            t(
                docstr!(
                    /// Header
                    ///
                    /// Footer
                ),
                "...",
            ),
            None
        );
    }

    /// Creating README file for the first time will insert markers,
    /// so subsequent invocations won't error
    #[test]
    fn create() {
        assert_str_eq!(
            ReadmeFile {
                contents: docstr!(
                    /// first
                )
                .to_string(),
                meta: ReadmeContentsMeta::NewlyCreated
            }
            .to_readme()
            .unwrap(),
            docstr!(
                /// <!-- cargo-reedme: start -->
                ///
                /// first
                ///
                /// <!-- cargo-reedme: end -->
                ///
            )
        );
    }

    #[test]
    fn insert() {
        let output = t(
            docstr!(
                /// Header
                ///
                /// <!-- cargo-reedme -->
                ///
                /// Footer
            ),
            "hello world",
        )
        .unwrap();

        assert_str_eq!(
            output,
            docstr!(
                /// Header
                ///
                /// <!-- cargo-reedme: start -->
                ///
                /// hello world
                ///
                /// <!-- cargo-reedme: end -->
                ///
                /// Footer
            )
        );
    }

    #[test]
    fn update() {
        let output = t(
            docstr!(
                /// Header
                ///
                /// <!-- cargo-reedme: start -->
                ///
                /// hello world
                ///
                /// <!-- cargo-reedme: end -->
                ///
                /// Footer
            ),
            "goodbye moon",
        )
        .unwrap();

        assert_str_eq!(
            output,
            docstr!(
                /// Header
                ///
                /// <!-- cargo-reedme: start -->
                ///
                /// goodbye moon
                ///
                /// <!-- cargo-reedme: end -->
                ///
                /// Footer
            )
        );
    }
}
