//! # Features
//!
//! ## Generate `README.md` from documentation comments in `lib.rs`
//!
//! Running `cargo reedme` will take your doc comments and generate a README from them. This `src/lib.rs`:
//!
//! ```rust
//! //! Hello, world!
//! ```
//!
//! Generates the following `README.md`:
//!
//! ```markdown
//! <!-- cargo-reedme: start -->
//!
//! Hello, world!
//!
//! <!-- cargo-reedme: end -->
//! ```
//!
//! If the `README.md` file already exists, it must have a `<!-- cargo-reedme -->` somewhere inside of it. If the `README.md` contains the following:
//!
//! ```markdown
//! # my_crate
//!
//! <!-- cargo-reedme -->
//! ```
//!
//! Running `cargo reedme` will replace that `<!-- cargo-reedme -->` with documentation from `lib.rs`:
//!
//! ```markdown
//! # my_crate
//!
//! <!-- cargo-reedme: start -->
//!
//! Hello, world!
//!
//! <!-- cargo-reedme: end -->
//! ```
//!
//! Further invocations of `cargo reedme` update the inserted region
//!
//! ## Link mapping
//!
//! Intra-doc links will be transformed into absolute URLs:
//!
//! ```rust,ignore
//! //! This data structure is [`serde_json::Value`](Value).
//! struct Value;
//! ```
//!
//! The above generate the following `README.md`:
//!
//! ```markdown
//! This data structure is [`serde_json::Value`](https://docs.rs/serde_json/1.0.149/serde_json/enum.Value.html).
//! ```
//!
//! The generated link format is fully configurable.
//!
//! ## Workspace support
//!
//! Generate `README.md`s for all crates in your workspace with a single command!
//!
//! Supports `--workspace`, `--exclude`, and `--package`
//!
//! ## Cargo features
//!
//! Supports `--all-features`, `--features`, and `--no-default-features`
//!
//! ## Code blocks transformation
//!
//! Code blocks will have `rust` language added, and hidden lines (starting with `#`) will be removed:
//!
//! ````rust,ignore
//! //! An example program:
//! //!
//! //! ```
//! //! # fn main() {
//! //! // "hello world" in Rust
//! //! println!("Hello, world!");
//! //! # }
//! //! ```
//! ````
//!
//! The above generates the following `README.md`:
//!
//! ````markdown
//! An example program:
//!
//! ```rust
//! // "hello world" in Rust
//! println!("Hello, world!");
//! ```
//! ````
//!
//! ## Macro expansion
//!
//! Macros in doc comments get properly expanded:
//!
//! ````rust,ignore
//! //! ```toml
//! //! [dependencies]
//! #![doc = concat!("derive_aliases = '", env!("CARGO_PKG_VERSION"), "'")]
//! //! ```
//! ````
//!
//! The above generates the following `README.md`:
//!
//! ````markdown
//! ```toml
//! [dependencies]
//! derive_aliases = '0.4'
//! ```
//! ````
//!
//! Notice that the `concat!` and inner `env!` macro was expanded appropriately.
//!
//! ## Check mode
//!
//! Run `cargo-reedme` as part of your CI pipeline!
//!
//! The `--check` flag is used to make sure PRs keep the `README.md` up to date with `lib.rs` doc comments.
//!
//! An example workflow that runs `cargo reedme --check` on every commit and PR:
//!
//! ```yaml
//! # .github/workflows/cargo-reedme.yaml
//! name: cargo-reedme
//! on:
//!   pull_request:
//!   push:
//!     branches:
//!       - main
//!
//! jobs:
//!   cargo-reedme:
//!     runs-on: ubuntu-latest
//!     steps:
//!       - uses: actions/checkout@v6
//!
//!       - uses: actions-rust-lang/setup-rust-toolchain@v1
//!
//!       - run: cargo install --locked cargo-reedme
//!
//!       - run: cargo-reedme --check
//! ```
//!
//! On failure, the program exits with a non-zero exit code and prints a colorful diff between the **expected** and **actual** `README.md` files
//!
//! ## Use programmatically from scripts
//!
//! The `--json` flag can be used to have `cargo-reedme` do all computation but not write any files, so you can
//! do with that data as you please.
//!
//! You can also use `cargo-reedme` as a crate. 95% of the `cargo-reedme`'s logic lives in a single, pure function `cargo_reedme::resolve`
//! which does no IO. It has the following signature:
//!
//! ```ignore
//! pub fn resolve(world: &World) -> Result<Output>
//! ```
//!
//! You can take a look at `main.rs` to see how this function is called
//!
//! ## Config
//!
//! You can configure the behavior of `cargo-reedme` via the crate-level `[package.metadata]` table in `Cargo.toml`:
//!
//! ```toml
//! # project/crates/foo_bar/Cargo.toml
//!
//! [package.metadata.cargo-reedme]
//! # ... your settings go here ...
//! ```
//!
//! ...or the workspace-level `[workspace.metadata]` table
//!
//! ```toml
//! # project/Cargo.toml
//!
//! [workspace.metadata.cargo-reedme]
//! # ... your settings go here ...
//! ```
//!
//! The default config is this:
//!
//! ```toml
#![doc = include_str!("../default_config.toml")]
//! ```
//!
//! Fun fact: This README itself is generated by `cargo reedme`. The above TOML is added from the [`default_config.toml`](https://github.com/nik-rev/cargo-reedme/blob/main/default_config.toml) file like this:
//!
//! ```ignore
//! #![doc = include_str!("../default_config.toml")]
//! ```
//!
//! # Inspired by
//!
//! - [`cargo-readme`](https://github.com/webern/cargo-readme)
//! - [`cargo-rdme`](https://github.com/orium/cargo-rdme)
//!

use camino::Utf8PathBuf;
use cargo_metadata::Package;

use serde::{Deserialize, Serialize};

use crate::{
    config::Config,
    insert_into_readme::{ReadmeContentsMeta, ReadmeFile},
};
use eyre::{Context as _, ContextCompat as _, Result};

pub mod world;

pub use world::World;

mod config;
pub mod insert_into_readme;
mod intralinks;
mod markdown;
mod replace_content;

/// Output of the program, with all computed README paths
#[derive(Serialize, Deserialize)]
pub struct Output {
    /// Version of the cargo-reedme when it generated the output
    pub version: semver::Version,
    /// List of generated README files
    pub readmes: Vec<GeneratedReadme>,
    /// Errors that were encountered while processing the READMEs
    #[serde(skip)]
    pub errors: Vec<eyre::Report>,
}

/// Data about individual README files
#[derive(Serialize, Deserialize)]
pub struct GeneratedReadme {
    /// Path to the README file
    pub path: Utf8PathBuf,
    /// Cargo package, to which this README belongs to
    pub package: String,
    /// Full new contents of the README file
    pub file: ReadmeFile,
    /// Content extracted from documentation comments, with
    /// zero processing applied
    pub original_doc_comments: String,
    /// Configuration that was used to generate this README file
    pub config: Config,
}

pub fn resolve(world: &World) -> Result<Output> {
    let mut metadata_cmd = world.input_manifest.metadata();

    // Takes into account selected features via --feature
    world.input_features.forward_metadata(&mut metadata_cmd);

    let metadata = metadata_cmd
        .exec()
        .context("failed to obtain Cargo metadata")?;

    // This takes into account selected packages such as via --package
    let (pkgs, _excluded_packages) = world.input_workspace.partition_packages(&metadata);

    let mut readmes = Vec::new();
    let mut errors = Vec::new();

    for pkg in pkgs {
        let result = (|| -> Result<GeneratedReadme> {
            let config = Config::new(metadata.workspace_metadata.clone(), pkg.metadata.clone());

            let (generated_readme, original_doc_comments) =
                generate_readme_for_package(world, pkg, &config, &metadata).with_context(|| {
                    format!("failed to generate README for package `{}`", pkg.name)
                })?;

            let readme_path = get_readme_path_for_package(pkg).with_context(|| {
                format!("failed to get `README.md` path for package `{}`", pkg.name)
            })?;

            let original_readme = match (world.read_file)(&readme_path) {
                Ok(contents) => Some(contents),
                // if this file doesn't exist, we will create it
                Err(err) if err.kind() == std::io::ErrorKind::NotFound => None,
                Err(err) => return Err(err.into()),
            };

            // NOTE: not .map() due to ownership issues
            let new_readme = match original_readme {
                Some(original_readme) => {
                    let meta = match insert_into_readme::UsersReadmeParts::new(&original_readme) {
                        Some(ok) => ReadmeContentsMeta::InsertedIntoUsersReadme(ok),
                        None => ReadmeContentsMeta::ErrorMarkerMissing,
                    };

                    ReadmeFile {
                        contents: generated_readme,
                        meta,
                    }
                }
                None => ReadmeFile {
                    contents: generated_readme.to_string(),
                    meta: ReadmeContentsMeta::NewlyCreated,
                },
            };

            Ok(GeneratedReadme {
                path: readme_path,
                file: new_readme,
                original_doc_comments,
                package: pkg.name.to_string(),
                config,
            })
        })();

        match result {
            Ok(ok) => readmes.push(ok),
            Err(err) => errors.push(err),
        }
    }

    Ok(Output {
        version: VERSION,
        readmes,
        errors,
    })
}

const VERSION: semver::Version = semver::Version::new(
    konst::unwrap_ctx!(konst::primitive::parse_u64(env!("CARGO_PKG_VERSION_MAJOR"))),
    konst::unwrap_ctx!(konst::primitive::parse_u64(env!("CARGO_PKG_VERSION_MINOR"))),
    konst::unwrap_ctx!(konst::primitive::parse_u64(env!("CARGO_PKG_VERSION_PATCH"))),
);

/// For a given Cargo package, returns contents of generated README.md
fn generate_readme_for_package(
    world: &World,
    pkg: &Package,
    config: &Config,
    workspace_metadata: &cargo_metadata::Metadata,
) -> Result<(String, String)> {
    let krate =
        (world.rustdoc_json_for_crate)(pkg, workspace_metadata).context("failed to run rustdoc")?;

    let root = krate
        .index
        .get(&krate.root)
        .expect("rustdoc's root item is a valid item");

    // Get the link map, which for [main function](main) creates: { "main": "https://example.com" }
    let links = intralinks::create_links(pkg, config, &krate);

    let docs = root.docs.as_deref().unwrap_or_default();

    // All links in the markdown are rewritten to consider the link map, e.g. [main function](https://example.com)
    Ok((markdown::resolve_markdown(docs, links), docs.to_string()))
}

/// For the given Cargo package, gets the path to the package's README.md file
fn get_readme_path_for_package(pkg: &cargo_metadata::Package) -> Result<Utf8PathBuf> {
    let readme_path = match pkg.readme() {
        Some(path) => path,
        None => {
            let parent = pkg
                .manifest_path
                .parent()
                .context("manifest has no parent directory")?;

            parent.join("README.md")
        }
    };

    Ok(readme_path)
}
